version: 2

before:
  hooks:
    - make generate
    - go test -race ./...

release:
  disable: true

changelog:
  disable: true

archives:
  - id: default
    # use the "binary" format so GoReleaser skips creating an archive
    formats:
      - binary

builds:
  - id: lakerunner-cli
    main: ./main.go
    binary: lakerunner-cli
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -X main.commit={{ .Commit }}
      - -X main.version={{ .Version }}
    flags:
      - -trimpath

# Define how to build/push Docker images.
dockers:
  - goos: linux
    goarch: amd64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner-cli:v{{ .Version }}-amd64"
      - "public.ecr.aws/cardinalhq.io/lakerunner-cli:latest-dev-amd64"
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
  - goos: linux
    goarch: arm64
    dockerfile: Dockerfile
    use: buildx
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner-cli:v{{ .Version }}-arm64"
      - "public.ecr.aws/cardinalhq.io/lakerunner-cli:latest-dev-arm64"
    build_flag_templates:
      - --pull
      - --platform=linux/arm64
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.name={{.ProjectName}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.source={{.GitURL}}
docker_manifests:
  - name_template: "public.ecr.aws/cardinalhq.io/lakerunner-cli:v{{ .Version }}"
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner-cli:v{{ .Version }}-amd64"
      - "public.ecr.aws/cardinalhq.io/lakerunner-cli:v{{ .Version }}-arm64"
  - name_template: "public.ecr.aws/cardinalhq.io/lakerunner-cli:latest-dev"
    image_templates:
      - "public.ecr.aws/cardinalhq.io/lakerunner-cli:latest-dev-amd64"
      - "public.ecr.aws/cardinalhq.io/lakerunner-cli:latest-dev-arm64"
